name: CI (Luau formatting & lint)

on:
  push:
  pull_request:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stylua format check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

      - name: Selene lint
        uses: Kampfkarren/selene-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .
